name: Hackathon-AWS-Device-Farm-Automation 

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      browserFamily:
        description: 'Enter the browser family name like chrome, firefox, IE etc'
        default: 'chrome'
        # Input has to be provided for the workflow to run
        required: true
      projectType:
        description: 'Enter the project type name like mobile, desktop etc'
        default: 'desktop'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  Hackathon-AWS-Device-Farm-Automation:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout Code from github repo
      uses: actions/checkout@v3
      with:
        path: code
        ref: master
    - name: Set up Python
      uses: actions/setup-python@v4.3.0
      with:
        python-version: '3.10'
    - name: Install Project dependencies using pip
      run: |
          pushd $GITHUB_WORKSPACE/code
          python -m pip install -r requirements.txt
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
    - name: Install AWS CLI v2
      run: >
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o
        /tmp/awscliv2.zip
          
        unzip -q /tmp/awscliv2.zip -d /tmp
          
        rm /tmp/awscliv2.zip
          
        sudo /tmp/aws/install --update
          
        rm -rf /tmp/aws/
    - name: Set up JDK 8 For Allure
      uses: actions/setup-java@v1
      with:
        java-version: '8'
        distribution: Zulu OpenJDK
    - name: Setup Allure Binary
      run: >
        curl -sL https://github.com/allure-framework/allure2/releases/download/2.20.1/allure-2.20.1.tgz > /tmp/allure-2.20.1.tgz
        
        ls -la
        
        tar -xf /tmp/allure-2.20.1.tgz
        
        ls -la
        
        chmod -R +x /tmp/allure-2.20.1/bin
        
        export PATH=$PATH:/tmp/allure-2.20.1/bin
        
        allure --version
        
    - name: Run Test cases for desktop project
      run: >
        echo "Running Test cases on browser ${{ github.event.inputs.browserFamily }}"
        
        pushd $GITHUB_WORKSPACE/code
        
        # python main.py "${{ github.event.inputs.browserFamily }}"

